# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # define a package manager to update
  - package-ecosystem: "npm"
    # Docs: https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/
    directories:
      - "/" # bats-core
      - "/tests/test_helper/bats-*" # bats library
    schedule:
      interval: "weekly"
