name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    # where the job will run on
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ubuntu-latest
    steps:
      # `git config [OPTIONS] + git clone [OPTIONS]` in a nutshell
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Bats Docker image
        run: docker pull bats/bats:latest

      - name: Test
        shell: bash
        env:
          TERM: xterm
        run: ./test.sh "tests"
